### ISSUE TITLE
Worst docs ever

### ISSUE THREAD

**Issue by notresponding2u** [MicrosoftDocs/Advertising-docs#1011]
Why so complex?? It is not clear, to what endpoint the requests should be done. Weird links, weird naming, some make sense, some doesn't. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc851aa-b0fb-14fc-097a-5471fc5557b9
* Version Independent ID: 2a0eaeb7-ebd6-720e-d523-80451b1c984f
* Content: [Bing Ads API Overview - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/guides/?view=bingads-13)
* Content Source: [Advertising/bingads-13/guides/index.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-13/guides/index.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
I agree there are opportunities to improve the API and the documentation. Please feel free to share specific suggestions or questions here, in the Bing Ads API developer forum ([advertising-api](https://docs.microsoft.com/en-us/answers/topics/advertising-api.html)), or [contact support](https://about.ads.microsoft.com/en-us/microsoft-advertising-support).
