### ISSUE TITLE
PowerShell script not working 

### ISSUE THREAD

**Issue by jieliuhk** [MicrosoftDocs/Advertising-docs#1029]
Powershell in https://docs.microsoft.com/en-us/advertising/guides/authentication-oauth-quick-start?view=bingads-13 quick start sandbox not working:

![image](https://user-images.githubusercontent.com/59852822/126824904-2ddffb27-9bba-42e4-8648-13d77df98984.png)

added -UseBasicParsing in line 12 resolved the problem:

![image](https://user-images.githubusercontent.com/59852822/126825066-b2c21498-3cb0-44c4-8df2-8b3eca367b61.png)

**Comment by eric-urban** [comment]
@jieliuhk - Thanks for letting me know. This is the first time I heard about any issue with the script. In any case we'll keep this in mind going forward.
