### ISSUE TITLE
authenticating from serverless-worker system

### ISSUE THREAD

**Issue by pentium10** [MicrosoftDocs/Advertising-docs#1039]
Hi @eric-urban 
I am trying to figure out how to run authentication in a serverless environment. 

I am working with Reports, and pulling out campaign stats. 
The bing SDK code works fine with Outh authentication, but now I need to 
- migrate credentials to a secret store
- read and authenticate on server side
- all this in serverless environment 

is it possible to authenticate with a secret ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53342393-eeda-5ea9-334e-557f75f47613
* Version Independent ID: be7a8696-014d-2e14-9f26-716f458dab8c
* Content: [Authentication With the SDKs - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/guides/sdk-authentication?view=bingads-13#oauth)
* Content Source: [Advertising/bingads-13/guides/sdk-authentication.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-13/guides/sdk-authentication.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@pentium10 - You can register a web app and use the client secret. If using SDKs please see OAuthWebAuthCodeGrant. You still need to get initial consent via UI. Please see [I want to run my application without user interaction. How can I authenticate without getting prompted for permission to use Microsoft Advertising credentials?](https://docs.microsoft.com/en-us/advertising/guides/faq?view=bingads-13#i-want-to-run-my-application-without-user-interaction--how-can-i-authenticate-without-getting-prompted-for-permission-to-use-microsoft-advertising-credentials---).
