### ISSUE TITLE
How to include transaction.xsd and common_types.xsd when validate the xml?

### ISSUE THREAD

**Issue by jieliuhk** [MicrosoftDocs/Advertising-docs#1049]
[Enter feedback here]

transaction.xsd required transaction.xsd and common_types.xsd, how to include it when valid the XML? 

![image](https://user-images.githubusercontent.com/59852822/131019246-a4972635-c5cc-4cd9-98b9-474347d70463.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14be8488-6a9f-1604-37ae-71f564d27036
* Version Independent ID: 72ef119e-ec17-a558-2f0e-8b43f09a215f
* Content: [Validating your Transaction Message - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/transaction-message/validate-transaction-message)
* Content Source: [Advertising/transaction-message/validate-transaction-message.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/transaction-message/validate-transaction-message.md)
* Service: **bing-ads-hotel-service**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
PR is merged https://github.com/MicrosoftDocs/Advertising-docs/pull/1050
