### ISSUE TITLE
Hourly aggregation TimePeriod format is broken in so many ways

### ISSUE THREAD

**Issue by huss01** [MicrosoftDocs/Advertising-docs#365]
1. Date format is inconsistent with all other aggregation types which use YYYY-MM-DD
2. Documented format is incorrect, the actual format is "m/d/y 12:00:00 AM|h"
3. According to the description,"12:00:00" can be ignored. Why is it included?
4. If a click was received between 23:00 and 23:59 on March 14, 2018 the documentation states that the TimePeriod for that would be "3/15/2018 12:00:00 AM|0". But then the date in the TimePeriod is not the date of the click. Is this really correct?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f012cd3-e500-b9c0-c0cb-43e1627049f8
* Version Independent ID: 4f752878-4a60-aeae-2e92-2915c548722d
* Content: [Reports - Bing Ads](https://docs.microsoft.com/en-us/bingads/guides/reports?view=bingads-12#timeperiod)
* Content Source: [BingAds/bingads-12/guides/reports.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/live/BingAds/bingads-12/guides/reports.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@huss01 thanks for the feedback. We have updated the documentation to clarify 2) and correct 4). I agree the format issues you mentioned per 1) and 3) should be fixed in a future API version e.g., YYYY-MM-DD|h. Our team is tracking this request. Please let me know if you have any follow up questions or concerns.
