### ISSUE TITLE
I do not see where to put the password

### ISSUE THREAD

**Issue by chanmmn** [MicrosoftDocs/Advertising-docs#527]
Frankly I saw a place I can put in my id.
private static string _clientId = "&lt;clientidgoeshere&gt;";  
But where to put in the password? 
Authenticating should have password. I am looking for a code to enter the username and password without any pop up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 640abf04-4f6a-cc4b-f3c3-292342f46ae4
* Version Independent ID: 5614d952-33e4-0492-7695-7c693702e564
* Content: [Authenticating Microsoft Account Credentials Code Example - Bing Ads](https://docs.microsoft.com/en-us/bingads/shopping-content/code-example-authentication-oauth)
* Content Source: [BingAds/shopping-content/code-example-authentication-oauth.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/master/BingAds/shopping-content/code-example-authentication-oauth.md)
* Service: **shopping-content-api**
* GitHub Login: @swhite-msft
* Microsoft Alias: **scottwhi**

**Comment by swhite-msft** [comment]
@chanmmn, with OAuth, you'll always have a "pop up" (browser client) where the user has to log on and provide consent for your app to manage their resources.
