### ISSUE TITLE
Please verify which is the correct variable for submitting Size attribute for product. sizes or size?

### ISSUE THREAD

**Issue by Simprosys-InfoMedia** [MicrosoftDocs/Advertising-docs#539]
sizes

&lt;size&gt;	The available size of the product. The size value is user-defined but should be based on your target country.	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b877c29-9521-3269-f072-7764b375e0c7
* Version Independent ID: 7dafcd81-b075-7007-d9e2-0db48b80ce6c
* Content: [Products Resource - Bing Ads](https://docs.microsoft.com/en-us/bingads/shopping-content/products-resource#-request-and-response-objects)
* Content Source: [BingAds/shopping-content/products-resource.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/master/BingAds/shopping-content/products-resource.md)
* Service: **shopping-content-api**
* GitHub Login: @swhite-msft
* Microsoft Alias: **scottwhi**

**Comment by swhite-msft** [comment]
Depends on whether you're using JSON or XML. If you're using JSON:

  "sizes": [
    "2T",
    "3T"
  ],

And if you're using XML:

  <size>2T</size>
  <size>3T</size>

Hope that helps.

**Comment by swhite-msft** [comment]
Sorry, brackets didn't paste correctly.

<size>2T</size>
<size>3T</size>

**Comment by swhite-msft** [comment]
Grrr. Trying again...

\<size>2T\</size>
\<size>3T\</size>

**Comment by Simprosys-InfoMedia** [comment]
Hello MicrosoftDocs/BingAds-docs,

I am not concerned about how values to be used. but what should be the
correct variable name itself?

In this help doc:
https://docs.microsoft.com/en-us/bingads/shopping-content/products-resource.
It says "sizes" as well as "size". We are using json for Content API.

[image: image.png]

Please confirm and if needed please correct it in help doc.

Thanks,
Milan Vaghela
Simprosys InfoMedia

**Comment by swhite-msft** [comment]
If you're using JSON, use "sizes".  The table's column name says "JSON and XML Name." We'll look into making it more explicit in each table cell.
JSON: sizes
XML: size
