### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by scauglog** [MicrosoftDocs/Advertising-docs#556]
the code doesn't compile and when we change the type to match the API it fail with error code 109 token expired

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e77d29c-dc31-0a29-3e49-8f14ed2095fd
* Version Independent ID: 07f4aa06-335f-9558-0d77-1988683f8ae0
* Content: [Walkthrough: Bing Ads Desktop Application in Java - Bing Ads](https://docs.microsoft.com/en-us/bingads/guides/walkthrough-desktop-application-java?view=bingads-12#feedback)
* Content Source: [BingAds/bingads-12/guides/walkthrough-desktop-application-java.md](https://github.com/MicrosoftDocs/BingAds-docs/blob/master/BingAds/bingads-12/guides/walkthrough-desktop-application-java.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@scauglog thanks for catching the compile issue. I've fixed it in my local branch, and will refresh the documentation next opportunity. 

The 109 [error](https://docs.microsoft.com/en-us/bingads/guides/operation-error-codes?view=bingads-12) indicates that your access token has expired. You can [refresh](https://github.com/BingAds/BingAds-Java-SDK/blob/master/examples/BingAdsDesktopApp/src/main/java/com/microsoft/bingads/examples/ExampleBase.java#L57) it using a the previous refresh token.

```java
((OAuthDesktopMobileAuthCodeGrant)(authorizationData.getAuthentication())).requestAccessAndRefreshTokens(refreshToken);
```

Best regards,
Eric

**Comment by scauglog** [comment]
Hi, great reactivity. I have found that the refresh token problem is due to a mismatch of environment. The code create a `OAuthDesktopMobileAuthCodeGrant`in Production (line 34) but it create `ServiceClient` for sandbox (line 88).

**Comment by eric-urban** [comment]
@scauglog great feedback, and we'll also update the sample to centralize the environment setting.
