### ISSUE TITLE
Please provide mapping to standard tz database

### ISSUE THREAD

**Issue by jpuck** [MicrosoftDocs/Advertising-docs#600]
Thank you for the list of [report timezones][mstz].

Can you please provide a map to the standard [tz database][tzdb] names? It is time-consuming and error-prone to do this manually.

[mstz]:https://docs.microsoft.com/en-us/advertising/reporting-service/reporttimezone?view=bingads-13
[tzdb]:https://en.wikipedia.org/wiki/Tz_database

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2a7393a-a737-d0b4-98a3-ded405b8e3c4
* Version Independent ID: 3d32e65f-34ad-2bc5-8190-891a825c25ed
* Content: [ReportTimeZone Value Set - Reporting - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/reporting-service/reporttimezone?view=bingads-13)
* Content Source: [Advertising/bingads-13/reporting-service/reporttimezone.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-13/reporting-service/reporttimezone.md)
* Service: **bing-ads-reporting-service**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@jpuck thanks for the suggestion. I'm sorry for the inconvenience but according to the feature team we do not have such a mapping in the code. We document the time zone contract provided by the Reporting API.
