### ISSUE TITLE
Report Download URL

### ISSUE THREAD

**Issue by aleinv18** [MicrosoftDocs/Advertising-docs#605]
Hi,

how is it possible that in some accounts the report request doesn't response the user location report URL and others give it?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663008b6-1280-9ad2-7f46-94b12b531920
* Version Independent ID: b679e12f-a226-d24b-d24e-92ff8a26bf66
* Content: [Report Requests Code Example - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/guides/code-example-report-requests?view=bingads-12)
* Content Source: [Advertising/bingads-12/guides/code-example-report-requests.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-12/guides/code-example-report-requests.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@aleinv18 if there isn't any report data for the account, given the report time, filters, other request parameters, then no URL will be returned. Per the [doc](https://docs.microsoft.com/en-us/advertising/reporting-service/reportrequeststatus#reportdownloadurl): "Use the download URL only if the Status element is set to Success. Even when the Status is set to Success, this element can be nil if no data is available for the submitted report parameters."
