### ISSUE TITLE
get-started.py

### ISSUE THREAD

**Issue by Chethan1015** [MicrosoftDocs/Advertising-docs#629]
Hello,

I am getting the below message when I run the code 'get-started.py' given on walkthrough-desktop-application-python. I am presently using a sandbox account. Need help in getting this solved as I am new to python and APIs.  

Message - 
GetUser:
GetUser() got an unexpected keyword argument 'IncludeLinkedAccountIds'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c91c556f-32a1-5c86-78f1-4732659639bf
* Version Independent ID: ff8c8e06-7ae0-b6a9-c9dc-4d4a534027a2
* Content: [Walkthrough: Bing Ads API Desktop Application in Python - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/guides/walkthrough-desktop-application-python?view=bingads-13#code)
* Content Source: [Advertising/bingads-13/guides/walkthrough-desktop-application-python.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-13/guides/walkthrough-desktop-application-python.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@Chethan1015 thanks for the heads up! We will update it to match [this working example](https://github.com/BingAds/BingAds-Python-SDK/blob/master/examples/v13/auth_helper.py#L49) i.e., remove IncludeLinkedAccountIds when [migrating from v12 to v13](https://docs.microsoft.com/en-us/advertising/guides/migration-guide?view=bingads-13#customer-includelinkedaccountids).
