### ISSUE TITLE
IndentationError

### ISSUE THREAD

**Issue by leon-lei** [MicrosoftDocs/Advertising-docs#630]
Minor fix. On line 96, missing indent after if statement.

95 if authorization_data.authentication.state != CLIENT_STATE:
96       raise Exception("The OAuth response state does not match the client request state.")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c91c556f-32a1-5c86-78f1-4732659639bf
* Version Independent ID: ff8c8e06-7ae0-b6a9-c9dc-4d4a534027a2
* Content: [Walkthrough: Bing Ads API Desktop Application in Python - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/guides/walkthrough-desktop-application-python?view=bingads-13#feedback)
* Content Source: [Advertising/bingads-13/guides/walkthrough-desktop-application-python.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-13/guides/walkthrough-desktop-application-python.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@leon-lei thanks for the heads up. We will update it to match this [working sample](https://github.com/BingAds/BingAds-Python-SDK/blob/master/examples/v13/auth_helper.py#L106).
