### ISSUE TITLE
Operation error 474

### ISSUE THREAD

**Issue by pedroacuma** [MicrosoftDocs/Advertising-docs#638]
Operation error 474 (Required search predicate is missing) is missing in the documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f12121c1-58eb-b113-6522-e0380b04dcb7
* Version Independent ID: df47cf3c-eb8d-6de5-58d7-7f798687944e
* Content: [Bing Ads API Operation Error Codes - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/guides/operation-error-codes?view=bingads-12#feedback)
* Content Source: [Advertising/bingads-12/guides/operation-error-codes.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-12/guides/operation-error-codes.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@pedroacuma thanks for letting us know. We'll add it to the documentation.

**Comment by eric-urban** [comment]
@pedroacuma the docs are update. Thanks again
