### ISSUE TITLE
Inconsistent column documentation

### ISSUE THREAD

**Issue by denisthedeveloper** [MicrosoftDocs/Advertising-docs#639]
In this site: https://docs.microsoft.com/en-us/advertising/guides/migration-guide?view=bingads-13
you've documented the section "**Replaced Some Impression Share Columns**" in which you say that you've removed a few columns from a few value sets. But the same columns that you say have been removed appear in the **Column Restrictions** site: https://docs.microsoft.com/en-us/advertising/guides/reports?view=bingads-13#columnrestrictions.
For example, in the restricted columns for the AdGroupPerformanceReportRequest SOAP action you've documented the column "ImpressionLostToAdRelevancePercent" in the **Impression Share Performance Statistics**, but this column is said to have been removed in the Migration Guide to V13.

I think you need to update the **Column Restrictions** documentation.

**Comment by eric-urban** [comment]
@denisthedeveloper you are correct, thanks for letting us know! We'll update it.

**Comment by eric-urban** [comment]
@denisthedeveloper the docs are update. Thanks again
