### ISSUE TITLE
Schema has two properies defined as "campaign" - confusing to say the least

### ISSUE THREAD

**Issue by LucasZapico** [MicrosoftDocs/Advertising-docs#650]
[Enter feedback here]

The schema called out below has two properties defined as "Campaign". The contents on the right hand side only have one campaign attributed defined. 

If there are two campaign properties. It would be very helpful to use unique naming conventions and have it called out in the docs. 

```csv
Type,Status,Id,Parent Id,Campaign,Campaign,Client Id,Modified Time,Bid Adjustment,Name,Audience Id,Audience
Format Version,,,,,,,,,6.0,,
Campaign Custom Audience Association,Paused,,-1111,,,ClientIdGoesHere,,10,,CustomAudienceIdHere,My Custom Audience
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c90b1986-084d-4a62-0c28-56ac961c3c5e
* Version Independent ID: 1f1d524c-7091-ad8e-937a-9d1af55fdec5
* Content: [Campaign Custom Audience Association Record - Bulk - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/bulk-service/campaign-custom-audience-association?view=bingads-12)
* Content Source: [Advertising/bingads-12/bulk-service/campaign-custom-audience-association.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-12/bulk-service/campaign-custom-audience-association.md)
* Service: **bing-ads-bulk-service**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@LucasZapico that's a typo, thanks for reporting it! There should be only one [Campaign](https://docs.microsoft.com/en-us/advertising/bulk-service/campaign-custom-audience-association?view=bingads-12#campaign) field/column in the bulk file. We'll update the docs.

**Comment by eric-urban** [comment]
@LucasZapico the docs are updated. Thanks again
