### ISSUE TITLE
Bulk schema format error

### ISSUE THREAD

**Issue by LucasZapico** [MicrosoftDocs/Advertising-docs#671]
The schema called out below seems to be formatted incorrectly. There appears to be one delimiter missing in the second row.  After the ```Ad Schedule``` property entry the entries are shifted left by one. Thank you for your time. 

---
The following Bulk CSV example would add a new Action Ad Extension to the account's shared library. 

```csv
Type,Status,Id,Parent Id,ClientId,Language,Start Date,End Date,Name,Ad Schedule,Use Searcher Time Zone,Action Type,Action Text,Final Url,Mobile Final Url,Tracking Template,Final Url Suffix,Custom Parameter
Format Version,,,,,,,,6.0,,,,,,,,,
Action Ad Extension,Active,-10,7671275,ClientIdGoesHere,English,,12/31/2019,(Monday[09:00-21:00]);(Tuesday[09:00-21:00]);(Wednesday[09:00-21:00]);(Thursday[09:00-21:00]);(Friday[09:00-21:00]),false,ActNow,,https://www.contoso.com/womenshoesale,https://mobile.contoso.com/womenshoesale,,,{_promoCode}=PROMO1; {_season}=summer
```
---

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef8d18de-1e10-9e9a-a431-5046355c70e1
* Version Independent ID: 6b6f9b74-acfb-4ac4-e60d-b8dcae7631a4
* Content: [Action Ad Extension Record - Bulk - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/bulk-service/action-ad-extension?view=bingads-12)
* Content Source: [Advertising/bingads-12/bulk-service/action-ad-extension.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-12/bulk-service/action-ad-extension.md)
* Service: **bing-ads-bulk-service**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@LucasZapico thanks for reporting it! Have added a comma for proper alignment. You should see this live now, or in a few minutes.
