### ISSUE TITLE
For report column CampaignPerformanceReportColumn::CampaignLabels does not return label descriptions

### ISSUE THREAD

**Issue by WouterVeen** [MicrosoftDocs/Advertising-docs#674]
When adding CampaignLables to a report trough the PHP SDK only the label names are returned and not the descriptions of the labels.

**Comment by eric-urban** [comment]
@WouterVeen this is [by design](https://docs.microsoft.com/en-us/advertising/reporting-service/campaignperformancereportcolumn?view=bingads-13#campaignlabels). The report should return the name(s) only (delimited as applicable). Please let me know if you have any follow up questions.
