### ISSUE TITLE
API not recognizing 'measurement' columns

### ISSUE THREAD

**Issue by denisthedeveloper** [MicrosoftDocs/Advertising-docs#680]
I'm sending a POST request to https://reporting.api.bingads.microsoft.com/Api/Advertiser/Reporting/v13/ReportingService.svc and it works ok when I include many different 'dimensions' and 'measurements' in the Columns tag of the request body. But when I include ONLY 1 dimension column (AccountName) and the columns that are marked as restricted here in the "Impression Share Performance Statistics" column (https://docs.microsoft.com/en-us/advertising/guides/reports?view=bingads-13#columnrestrictions) the API throws this error:

"[NoMeasureSelected] The specified report request does not specify measurement columns (at least one is required). Please submit a report request with the required columns for this report type, and optionally additional columns that are to be included in the report."

It looks like the API doesn't recognize these columns that I'm requesting ARE measurement columns.

These are the columns that I'm sending (part of the SOAP request body):

&lt;AccountPerformanceReportColumn&gt;AbsoluteTopImpressionSharePercent&lt;/AccountPerformanceReportColumn&gt;
&lt;AccountPerformanceReportColumn&gt;ClickSharePercent&lt;/AccountPerformanceReportColumn&gt;
&lt;AccountPerformanceReportColumn&gt;ImpressionSharePercent&lt;/AccountPerformanceReportColumn&gt;
&lt;AccountPerformanceReportColumn&gt;ExactMatchImpressionSharePercent&lt;/AccountPerformanceReportColumn&gt;
&lt;AccountPerformanceReportColumn&gt;ImpressionLostToBudgetPercent&lt;/AccountPerformanceReportColumn&gt;
&lt;AccountPerformanceReportColumn&gt;ImpressionLostToRankAggPercent&lt;/AccountPerformanceReportColumn&gt;
&lt;AccountPerformanceReportColumn&gt;AccountName&lt;/AccountPerformanceReportColumn&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2019acfa-255a-745c-fd10-dbc9d0799dbb
* Version Independent ID: 187fe6cd-4e27-f948-80f4-37e3b901c5d0
* Content: [AccountPerformanceReportColumn Value Set - Reporting - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/reporting-service/accountperformancereportcolumn?view=bingads-13#feedback)
* Content Source: [Advertising/bingads-13/reporting-service/accountperformancereportcolumn.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-13/reporting-service/accountperformancereportcolumn.md)
* Service: **bing-ads-reporting-service**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@denisthedeveloper The service actually expects at least one **non-impression share** measure for these reports. We need a better message to convey this error. For now you can be assured this is by design. Thank you.

**Comment by eric-urban** [comment]
@denisthedeveloper the documentation is updated: "The report must include the following columns. As a general rule, each report must include at least one non-impression share attribute column and at least one performance statistics column." Thanks for your patience!
