### ISSUE TITLE
"Search Accounts" doc link goes to GetUser operation instead

### ISSUE THREAD

**Issue by barestides** [MicrosoftDocs/Advertising-docs#681]
all in the title

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8b60dea-2015-e556-8497-73bdb9d35949
* Version Independent ID: 23977ab8-e50f-4157-aac7-1d22f3ad3191
* Content: [Get Started With the Bing Ads API - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/guides/get-started?view=bingads-13#feedback)
* Content Source: [Advertising/bingads-13/guides/get-started.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-13/guides/get-started.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@barestides thanks for flagging this issue. The doc has been updated. Thank you again.
