### ISSUE TITLE
Good content, but...

### ISSUE THREAD

**Issue by seisenreich** [MicrosoftDocs/Advertising-docs#682]
Hello,
The page itself is high quality content, but you should display something that has to be done before Transaction Message before the Docs chapter about Transaction Messages IMHO.

Kind regards,
Steven Eisenreich

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2976faea-dc28-ba66-9863-a9f66566f292
* Version Independent ID: e4bffd93-cd11-7354-bc7f-6bf08f3604e0
* Content: [Hotel Feed - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/hotel-feed/hotel-feed#feedback)
* Content Source: [Advertising/hotel-feed/hotel-feed.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/hotel-feed/hotel-feed.md)
* Service: **hotel-ads-hotel-feed**
* GitHub Login: @swhite-msft
* Microsoft Alias: **scottwhi**

**Comment by swhite-msft** [comment]
Thanks for the feedback, Steven. We'll add a note as you suggest.
