### ISSUE TITLE
Url for authentication in sanbox seems to be wrong

### ISSUE THREAD

**Issue by seisenreich** [MicrosoftDocs/Advertising-docs#686]
When trying to use the given URL for getting a custom client ID instead of using the universal one documented elsewhere it does not seem to work.

When calling...
apps.dev.microsoft-int.com/#/appList—Endpoint for getting a sandbox client ID

...and after logging in with a sandbox MSA there is this text:
"Application registrations portal is no longer available for personal Microsoft accounts (Skype, Outlook, etc.) to register and manage converged applications. We recommend that you manage your existing applications and register new applications by using the App registrations (now Generally Available) experience in the Azure portal. Click this banner to launch the new and improved experience. "

With a link and a button on the site which both redirect to "https://login.windows-ppe.net/common/oauth2/authorize?resource=https%3a%2f%2fmanagement.core.windows.net%2f&response_mode=form_post&response_type=code+id_token&scope=user_impersonation+openid&state=OpenIdConnect.AuthenticationProperties%3dR1-33QJq3NKVMDZhQ9EujVbtdOLs4E3YT6Rbay7Am63up2RDXZV5I5L0BlhmnK31TJtbbtJ55d1aTa_YWbeZ90U9M_1UP5Eg1ePDMOwqo76Mr0Zhy1V1y1DXB0cfiLzOT8FG4mIgufsfGzV4BCtBhGK8fW4lmaWJg7RkR8U35Z1f9JeIz1oRkHtgdwvAsw2A9ZdQaUn2A9ChABlCthpQcOG9iHL8xgtbxa54BcwspdXl0fJ8ufpyO4aH-Iu6Ngxt0e2JVjKWz2rowieeFDF5N26rfAZ80nluR4Id7bNu1jGN-1qdjfD5i37Bjc52EXHoNbO7UvOHRzUn7qweVMFlQDcWJSldpw39LBQCJU6hgKg2WRpgUlzQO2ndfnUHjVaE&nonce=637054234817775960.MDhjODQzODgtMmUyOC00MGU5LWFmOGUtZGQyOTllNzk3N2RiOGRhNDAzYzgtMTI3My00NTAwLWEzMDItYWZjNTc3Njg2ZGMx&client_id=c44b4083-3bb0-49c1-b47d-974e53cbdf3c&redirect_uri=https%3a%2f%2fdf.onecloud.azure-test.net%2fsignin%2findex%2f%3ffeature.refreshtokenbinding%3dtrue&site_id=501430&client-request-id=92144760-1bd9-4240-8578-ece3b483ef06&x-client-SKU=ID_NET&x-client-ver=1.0.40306.1554" .

But there I cannot log in. Neither does this seem to be an internal url.
Trying to add "-int" right before the .net results in an error page with the message "Die Server-IP-Adresse von login.windows-ppe-int.net wurde nicht gefunden.".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc0ae13f-8c66-6094-1362-86a7faf514e6
* Version Independent ID: 22b617dc-8221-ccf2-c4d5-5f0011d401f2
* Content: [Get Started with the Hotel API - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/hotel-service/get-started)
* Content Source: [Advertising/hotel-service/get-started.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/hotel-service/get-started.md)
* Service: **hotel-ads-hotel-service**
* GitHub Login: @swhite-msft
* Microsoft Alias: **scottwhi**

**Comment by swhite-msft** [comment]
Thanks for letting us know, Steven. We'll that fixed.
