### ISSUE TITLE
Codes Missing

### ISSUE THREAD

**Issue by drew180** [MicrosoftDocs/Advertising-docs#703]
We're receiving error codes that are not listed here: 
Unrecognized error code: 8376
Unrecognized error code: 8364
Please update the list. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a88cadf1-985b-8173-f53f-ae5908e6a777
* Version Independent ID: b7c771dd-4328-6f14-b8ad-76cd7157fd21
* Content: [Editorial Reason Codes - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/guides/editorial-failure-reason-codes?view=bingads-13#feedback)
* Content Source: [Advertising/bingads-13/guides/editorial-failure-reason-codes.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-13/guides/editorial-failure-reason-codes.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@drew180 thanks for raising this issue. Both of these indicate a generic Policy Violation: "Your ad or website contains content that is not allowed on Microsoft Advertising." We'll update the doc with this information, and to find out more about your content please see the [policy guide](https://about.ads.microsoft.com/en-us/resources/policies) or [contact support](https://about.ads.microsoft.com/en-us/microsoft-advertising-support). Thank you.
