### ISSUE TITLE
Insufficient documentation

### ISSUE THREAD

**Issue by SeanMeh** [MicrosoftDocs/Advertising-docs#714]
An example showing how to specify multiple CampaignTypes would be nice.  I don't seem to be able to place them all in one CampaignType field, and having multiple CampaignType fields (one for each type) only seems to result in the first one being considered.

Better yet... it would be nice if I could just grab all campaigns regardless of CampaignType.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1326e875-47a5-074c-42a6-749099415ad1
* Version Independent ID: 2783c056-1316-247b-ccae-8dda24ef3186
* Content: [GetCampaignsByAccountId Service Operation - Campaign Management - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/campaign-management-service/getcampaignsbyaccountid?view=bingads-13#feedback)
* Content Source: [Advertising/bingads-13/campaign-management-service/getcampaignsbyaccountid.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-13/campaign-management-service/getcampaignsbyaccountid.md)
* Service: **bing-ads-campaign-management-service**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by SeanMeh** [comment]
If anyone else runs into this problem, I guess you can put them all in `CampaignType` after all, just space-delimited.

**Comment by eric-urban** [comment]
@SeanMeh thanks for the feedback! Documentation has been updated to clarify this should be space delimited.
