### ISSUE TITLE
Is this report still available ?

### ISSUE THREAD

**Issue by RoyBellingan** [MicrosoftDocs/Advertising-docs#718]
I do not see anywhere that report on the https://ui.ads.microsoft.com/Reporting/v2, also using the API asking for this report I receive a response like 
&lt;?xml version="1.0"?&gt;
&lt;s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"&gt;
  &lt;s:Header&gt;
    &lt;h:TrackingId xmlns:h="https://bingads.microsoft.com/Reporting/v13"&gt;c0883eda-b5d3-4174-b728-bec4c6c32f1d&lt;/h:TrackingId&gt;
  &lt;/s:Header&gt;
  &lt;s:Body&gt;
    &lt;PollGenerateReportResponse xmlns="https://bingads.microsoft.com/Reporting/v13"&gt;
      &lt;ReportRequestStatus xmlns:i="http://www.w3.org/2001/XMLSchema-instance"&gt;
        &lt;ReportDownloadUrl i:nil="true"/&gt;
        &lt;Status&gt;Success&lt;/Status&gt;
      &lt;/ReportRequestStatus&gt;
    &lt;/PollGenerateReportResponse&gt;
  &lt;/s:Body&gt;
&lt;/s:Envelope&gt;

So report is ready, but there is no url to download...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a18e439d-0d3c-4b83-2e25-8ed801151221
* Version Independent ID: 4d8b6efe-00bc-e6e9-4607-658ec71a66da
* Content: [ProfessionalDemographicsAudienceReportRequest Data Object - Reporting - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/reporting-service/professionaldemographicsaudiencereportrequest?view=bingads-13#feedback)
* Content Source: [Advertising/bingads-13/reporting-service/professionaldemographicsaudiencereportrequest.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-13/reporting-service/professionaldemographicsaudiencereportrequest.md)
* Service: **bing-ads-reporting-service**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@RoyBellingan per the [documentation](https://docs.microsoft.com/en-us/advertising/reporting-service/reportrequeststatus?view=bingads-13):

Use the download URL only if the Status element is set to Success. Even when the Status is set to Success, this element can be nil if no data is available for the submitted report parameters.

Please also note, the Professional demographics report is under 'Targeting' in the UI Reports tab. (There are no longer separate reports for the Audience network.) Please reach out if you have any follow up questions.

**Comment by RoyBellingan** [comment]
Thank you eric.
