### ISSUE TITLE
Empty response of GetBillingDocumentsInfo

### ISSUE THREAD

**Issue by Jor-G-ete** [MicrosoftDocs/Advertising-docs#720]
# SOLVED!: #719 
```python
self._start_date = datetime.strptime(start_date, '%Y%m%d')
self._end_date = datetime.strptime(end_date, '%Y%m%d')
DocumentsIds = self._customer_billing_service.GetBillingDocumentsInfo(
			AccountIds={'long':[0,1,2]},
			StartDate=self._start_date,
			EndDate=self._end_date
)
```
Now it has the problem that the soap response is been returned empty. As it happend in .NET

MESSAGE:
b'<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:TrackingId xmlns:h="https://bingads.microsoft.com/Billing/v13"> **The tracking id** </h:TrackingId></s:Header><s:Body><GetBillingDocumentsInfoResponse xmlns="https://bingads.microsoft.com/Billing/v13"><BillingDocumentsInfo xmlns:a="https://bingads.microsoft.com/Customer/v13/Entities" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"/></GetBillingDocumentsInfoResponse></s:Body></s:Envelope>'
DEBUG:suds.client:HTTP succeeded:
b'<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:TrackingId xmlns:h="https://bingads.microsoft.com/Billing/v13">**The tracking id**</h:TrackingId></s:Header><s:Body><GetBillingDocumentsInfoResponse xmlns="https://bingads.microsoft.com/Billing/v13"><BillingDocumentsInfo xmlns:a="https://bingads.microsoft.com/Customer/v13/Entities" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"/></GetBillingDocumentsInfoResponse></s:Body></s:Envelope>'

**Comment by eric-urban** [comment]
@Jor-G-ete in this case I suggest that you [contact support](https://about.ads.microsoft.com/en-us/microsoft-advertising-support) to find out why billing documents are not returned for your specific accounts. Also note, you can ask general questions here in the [API forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=BingAds).
