### ISSUE TITLE
Attributes stated as unsupported and ignored here are at least partially required (!)

### ISSUE THREAD

**Issue by seisenreich** [MicrosoftDocs/Advertising-docs#725]
We got feedback through our account manager, that an example transaction message xml file could not be uploaded.
The error message was "The &lt;Transaction&gt; element is missing the 'id' attribute. The transaction must include the user-defined ID".

The problem here is that on this documentation page it is stated, that the attribute id in Transaction Elements is unsupported and will be ignored. So we did not send it. Why send something stated to being ignored.

Please fix this. It's really confusing for developers trying to integrate this api.

KR

Steven Eisenreich

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e218724d-5458-aa9f-d9ba-9787d9af3412
* Version Independent ID: b8b92eff-817d-6439-517c-c4caa05af040
* Content: [Differences Between Google's and Bing's Transaction Message Usage - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/transaction-message/google-bing-transaction-message-differences)
* Content Source: [Advertising/transaction-message/google-bing-transaction-message-differences.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/transaction-message/google-bing-transaction-message-differences.md)
* Service: **hotel-ads-transaction-message**
* GitHub Login: @swhite-msft
* Microsoft Alias: **scottwhi**

**Comment by swhite-msft** [comment]
Thanks for letting us know. Yep, that is confusing especially when the reference topic and create topic both correctly state that it's required. We'll get that topic updated.
