### ISSUE TITLE
Insufficient documentation

### ISSUE THREAD

**Issue by SeanMeh** [MicrosoftDocs/Advertising-docs#740]
This request object is _way_ too complicated to have so little documentation around it.  There's a link above the example request that wants to link to a table of Request Body Elements, except that said table doesn't exist and it instead links to the Request Header Elements table.

This page is basically impossible to work with as is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 736b2dd2-dd03-fe6a-9227-be6969434e0d
* Version Independent ID: ac863201-9d5f-95f4-1b62-e6cbe6678e4b
* Content: [SubmitGenerateReport Service Operation - Reporting - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/reporting-service/submitgeneratereport?view=bingads-13)
* Content Source: [Advertising/bingads-13/reporting-service/submitgeneratereport.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-13/reporting-service/submitgeneratereport.md)
* Service: **bing-ads-reporting-service**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@SeanMeh good catch, and we've fixed the incorrect link to Request Body Elements. We've also added more details to the introduction and a link to the technical guide. Thanks!
