### ISSUE TITLE
components attributes docs are not right

### ISSUE THREAD

**Issue by seisenreich** [MicrosoftDocs/Advertising-docs#749]
Dear Advertising team,

I tried to upload a hotel feed with the attribute "addr2" in component elements of my listing elements.
Unfortunately the upload fails because of that as our account manager told us afterwards.

If you don't support addr2 yet it's totally fine. But please make a note in the same spot where the optional attribute is documented as you did e.g. for the language which must be "en" at the moment. 
This would make the developer's life a bit easier while implementing your api.

Kind regards, and keep up the good work!

Steven Eisenreich.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb407267-e4fc-873f-0a95-5ef0969df331
* Version Independent ID: c76d2db5-7a65-003e-6d00-69198985fab2
* Content: [Hotel Feed Reference - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/hotel-feed/reference#feedback)
* Content Source: [Advertising/hotel-feed/reference.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/hotel-feed/reference.md)
* Service: **hotel-ads-hotel-feed**
* GitHub Login: @swhite-msft
* Microsoft Alias: **scottwhi**

**Comment by swhite-msft** [comment]
Hello @seisenreich 

Thanks for bringing the issue to our attention. I've confirmed with our development team that addr2 and addr3 are supported fields. The team will work in the near future to ensure these two fields are used to match hotels. 

Best regards.
