### ISSUE TITLE
invalid_request error with the default code sample. I have followed every step correctly

### ISSUE THREAD

**Issue by sebomio** [MicrosoftDocs/Advertising-docs#792]
invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.
Please read :
https://github.com/microsoftgraph/msgraph-training-uwp/issues/31

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c91c556f-32a1-5c86-78f1-4732659639bf
* Version Independent ID: ff8c8e06-7ae0-b6a9-c9dc-4d4a534027a2
* Content: [Walkthrough: Bing Ads API Desktop Application in Python - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/guides/walkthrough-desktop-application-python?view=bingads-13#feedback)
* Content Source: [Advertising/bingads-13/guides/walkthrough-desktop-application-python.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-13/guides/walkthrough-desktop-application-python.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@sebomio to help determine whether we can isolate the issue to client ID can you please try one or both workaround for sandbox and production below? 

```python
# Sandbox
CLIENT_ID = 'db41b09d-6e50-4f4a-90ac-5a99caefb52f'
DEVELOPER_TOKEN='BBD37VB98'
ENVIRONMENT='sandbox'
```

```python
# Production
CLIENT_ID = '6731de76-14a6-49ae-97bc-6eba6914391e' # You can use this temporarily for a test
DEVELOPER_TOKEN='TODO'  # Please use your own production developer token.
ENVIRONMENT='production'
```

There may be an issue with app registration, so please also double check and/or register a new client ID via the steps [here](https://docs.microsoft.com/en-us/advertising/guides/authentication-oauth-identity-platform?view=bingads-13#registerapplication).
