### ISSUE TITLE
Recurring Error

### ISSUE THREAD

**Issue by jamie556apps** [MicrosoftDocs/Advertising-docs#795]
After following the steps above. I keep on getting the following error: 

&lt;s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"&gt;&lt;s:Body&gt;&lt;s:Fault&gt;&lt;faultcode xmlns:a="http://schemas.microsoft.com/ws/2005/05/addressing/none"&gt;a:ActionNotSupported&lt;/faultcode&gt;&lt;faultstring xml:lang="en-US"&gt;The message with Action \'\' cannot be processed at the receiver, due to a ContractFilter mismatch at the EndpointDispatcher. This may be because of either a contract mismatch (mismatched Actions between sender and receiver) or a binding/security mismatch between the sender and the receiver.  Check that sender and receiver have the same contract and the same binding (including security requirements, e.g. Message, Transport, None).&lt;/faultstring&gt;&lt;/s:Fault&gt;&lt;/s:Body&gt;&lt;/s:Envelope&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 736b2dd2-dd03-fe6a-9227-be6969434e0d
* Version Independent ID: ac863201-9d5f-95f4-1b62-e6cbe6678e4b
* Content: [SubmitGenerateReport Service Operation - Reporting - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/reporting-service/submitgeneratereport?view=bingads-13#feedback)
* Content Source: [Advertising/bingads-13/reporting-service/submitgeneratereport.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-13/reporting-service/submitgeneratereport.md)
* Service: **bing-ads-reporting-service**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@jamie556apps please consider posting the repro steps, including SOAP request and response (without credentials) via the [developer forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=BingAds) or [contact support](https://docs.microsoft.com/en-us/advertising/guides/handle-service-errors-exceptions?view=bingads-13#contact-support) for additional assistance.
