### ISSUE TITLE
Calling GoogleApis results in error

### ISSUE THREAD

**Issue by luukfiets** [MicrosoftDocs/Advertising-docs#802]
Calling GoogleApis gives back an ReferenceError: 'GoogleApis' is not defined. It's true, but I don't see where and how it should be defined. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4ce1cb-aa16-8029-013d-ccc04296287a
* Version Independent ID: 12fe3c13-f05f-0d16-799a-02652e3bf671
* Content: [Calling Google services - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/scripts/examples/calling-google-services#feedback)
* Content Source: [Advertising/scripts/examples/calling-google-services.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/scripts/examples/calling-google-services.md)
* Service: **bingads-scripts**
* GitHub Login: @swhite-msft
* Microsoft Alias: **scottwhi**

**Comment by swhite-msft** [comment]
Hello. Sorry for the late reply. GoogleApis is defined further down in the script. Look for this section:

var GoogleApis;
(function (GoogleApis) {

// A bunch of function for calling Google services...

})(GoogleApis || (GoogleApis = {}));

Hope this helps.
