### ISSUE TITLE
What about Responsive search ads?

### ISSUE THREAD

**Issue by nakitadog** [MicrosoftDocs/Advertising-docs#806]
Scripts are not returning Responsive search ads. Only expanded text ads.

**Comment by eric-urban** [comment]
@nakitadog I confirmed this is not on the near term roadmap. I suggest please submit a feature request via [Microsoft Advertising Feature Suggestions](https://microsoftadvertising.uservoice.com/forums/82363-microsoft-advertising-feature-suggestions). Thanks!
