### ISSUE TITLE
Sample Code Inside Anchor Tag

### ISSUE THREAD

**Issue by hambone-the-Great** [MicrosoftDocs/Advertising-docs#822]
There is some sample code on this page that is inside of an anchor tag, causing the sample code to behave like a link when hovering the mouse over the code example.

The anchor tag in question has the name attribute "secondexample". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 640abf04-4f6a-cc4b-f3c3-292342f46ae4
* Version Independent ID: 5614d952-33e4-0492-7695-7c693702e564
* Content: [Authenticating Microsoft Account Credentials Code Example - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/shopping-content/code-example-authentication-oauth)
* Content Source: [Advertising/shopping-content/code-example-authentication-oauth.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/shopping-content/code-example-authentication-oauth.md)
* Service: **shopping-content-api**
* GitHub Login: @swhite-msft
* Microsoft Alias: **scottwhi**

**Comment by swhite-msft** [comment]
Thanks much for letting us know. We'll get that fixed shortly.
