### ISSUE TITLE
How many conversion goals we could create for one account?

### ISSUE THREAD

**Issue by zgf** [MicrosoftDocs/Advertising-docs#827]
I didn't find this info in documents

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bffa690-9588-a53d-0050-6e1bc4092f75
* Version Independent ID: 02e44912-ab25-7148-47eb-cc0826ccb62e
* Content: [ConversionGoal Data Object - Campaign Management - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/campaign-management-service/conversiongoal?view=bingads-13)
* Content Source: [Advertising/bingads-13/campaign-management-service/conversiongoal.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-13/campaign-management-service/conversiongoal.md)
* Service: **bing-ads-campaign-management-service**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@zgf sorry for the delay! I am not aware of any limit, but I'll let you know. I'm waiting to hear back from the team.

**Comment by eric-urban** [comment]
@zgf here are the conversion goal limits in production:

- Account level limit: 1,000
- Customer level limit: 5,000

We are updating the documentation to clarify. 

Thank you!

**Comment by eric-urban** [comment]
@zgf thanks for your patience.. The doc is updated here: https://docs.microsoft.com/en-us/advertising/guides/entity-hierarchy-limits?view=bingads-13#conversiongoals
