### ISSUE TITLE
User Location Performance Report is mislabeled and incorrectly linked in Report Types page

### ISSUE THREAD

**Issue by pavan-kalyan** [MicrosoftDocs/Advertising-docs#836]
In [Report Types page](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-13/guides/report-types.md),
It should be `User Location Performance Report` instead of `User Location Performance Column`.
This would be in line with the remaining reports on that page. The link also needs to point to the right place.

**Comment by eric-urban** [comment]
@pavan-kalyan thanks for raising this issue. We'll update the documentation.
