### ISSUE TITLE
CampaignPerformanceReport's mutually exclusive Impression Share Performance Statistics out-of-date (Bing Reports Overview Page)

### ISSUE THREAD

**Issue by chris-ragsdale** [MicrosoftDocs/Advertising-docs#850]
In the [report overview](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-13/guides/reports.md#column-restrictions) page, under the "column restrictions" header, the set of mutually exclusive Impression Share Performance Statistics appear to be out-of-date for the CampaignPerformanceReport.

When I submit report requests including any of the listed Attributes and omitting all of the listed Impression Share Performance Statistics, I get the "RestrictedColumnCombinations" error (code 2064). However, when I submit report requests including all listed Impression Share Performance Statistics and omitting all listed Attributes (and CustomerId, CustomerName, DeliveredMatchType), the requests are successful.

**Comment by chris-ragsdale** [comment]
I was able to track down the issue to these additional columns:
* AbsoluteTopImpressionShareLostToRankPercent
* AbsoluteTopImpressionShareLostToBudgetPercent
* AbsoluteTopImpressionRatePercent
* TopImpressionShareLostToRankPercent
* TopImpressionShareLostToBudgetPercent
* TopImpressionSharePercent
* TopImpressionRatePercent

**Comment by eric-urban** [comment]
@chris-ragsdale thanks for raising this issue. We'll double check all requirements and get back to you.

**Comment by eric-urban** [comment]
@chris-ragsdale the doc is updated. Thanks for your patience!
