### ISSUE TITLE
Duplicate Report Column - cause error

### ISSUE THREAD

**Issue by rontubis** [MicrosoftDocs/Advertising-docs#868]
Hello,

On Reporting Code Example (c#) - There is a duplicate raw (report column) and it cause an error when you request report from API. 

On function GetAdPerformanceReportRequest()

the duplicate raw is:
AdPerformanceReportColumn.Spend 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fbdead6-cbf5-efd4-45aa-bf3383a3b074
* Version Independent ID: b679e12f-a226-d24b-d24e-92ff8a26bf66
* Content: [Report Requests Code Example - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/guides/code-example-report-requests?view=bingads-13)
* Content Source: [Advertising/bingads-13/guides/code-example-report-requests.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-13/guides/code-example-report-requests.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@rontubis thanks for the heads up. We'll update the sample.
