### ISSUE TITLE
Feedback: More examples

### ISSUE THREAD

**Issue by Ed-Ed** [MicrosoftDocs/Advertising-docs#881]
For **ApplyProductPartitionActions Service Operation - Campaign Management**, and other pages, I feel like there need to be more examples. For example, with **ApplyProductPartitionActions**, there is an _add_, _update_, and _delete_ action. The bullet-points cover them briefly, but in my opinion, there should be unique examples of the **Request** for each action, making figuring out what I need to supply much easier.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b32ed26c-9984-a943-7bfd-b40de2175967
* Version Independent ID: 86531dd9-a58a-d3dd-de9e-260935155052
* Content: [ApplyProductPartitionActions Service Operation - Campaign Management - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/campaign-management-service/applyproductpartitionactions?view=bingads-13#feedback)
* Content Source: [Advertising/bingads-13/campaign-management-service/applyproductpartitionactions.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-13/campaign-management-service/applyproductpartitionactions.md)
* Service: **bing-ads-campaign-management-service**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@Ed-Ed please note there are Add and Update examples [here](https://docs.microsoft.com/en-us/advertising/guides/code-example-product-ads?view=bingads-13). Does this help?

**Comment by Ed-Ed** [comment]
Sorry I should have been more clear in the feedback. I was specifically referring to the XML. I have seen the C# examples, but there's not really helpful.

This isn't an issue I'm having anymore, just a suggestion.

**Comment by eric-urban** [comment]
@Ed-Ed thanks for clarifying! The xml template is generated by a tool to show the order of the body and header elements for the SOAP request. For supported types that you can use with this service operation, we refer readers to the reference details above on the same page.
