### ISSUE TITLE
Missing download for enum values like currencies and minimum CPCs

### ISSUE THREAD

**Issue by markusheiden** [MicrosoftDocs/Advertising-docs#923]
It would be nice, if there were CSV download files containing the described enums lists (e.g. currencies and minimum CPCs), like e.g. AdWords provides them. That way I don't need to copy and paste those values into my application.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c1f5654-24d7-bfd3-5ec9-926ab3eda085
* Version Independent ID: 4db7c1de-3645-6e68-788f-cf9fc4f1e6fc
* Content: [Microsoft Advertising Currencies - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/guides/currencies?view=bingads-13)
* Content Source: [Advertising/bingads-13/guides/currencies.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-13/guides/currencies.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@markusheiden thanks for the feedback! In case you only need the enums, at least in the short term, please see the [CurrencyCode value set](https://docs.microsoft.com/en-us/advertising/customer-management-service/currencycode?view=bingads-13). For the CSV download, I suggest please [open a feature request](https://microsoftadvertising.uservoice.com/forums/82363-microsoftadvertising-feature-suggestion?category_id=16945).
