### ISSUE TITLE
Please provide direct download links, not just via the API

### ISSUE THREAD

**Issue by markusheiden** [MicrosoftDocs/Advertising-docs#924]
Please provide a direct download link for the location codes, not just via the API. With AdWords it is much easier, because they provide a CSV download.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 749cc90f-2a91-02b7-8d03-f0821e493cdb
* Version Independent ID: c622fe8a-b289-5fff-48ab-f261b95adb1c
* Content: [Geographical Location Codes - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/guides/geographical-location-codes?redirectedfrom=MSDN&view=bingads-13)
* Content Source: [Advertising/bingads-13/guides/geographical-location-codes.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-13/guides/geographical-location-codes.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@markusheiden - You can also download the location codes from the [Microsoft Advertising Developer Portal](https://developers.ads.microsoft.com/Account). You must be signed in to the developer portal with a Microsoft account user who has Microsoft Advertising credentials. Then choose the **Downloads** tab on the **Accounts** page.
