### ISSUE TITLE
404 Script Error

### ISSUE THREAD

**Issue by nintendork78** [MicrosoftDocs/Advertising-docs#941]
Thank you for sharing this script. I am not sure where I am going wrong, though, as when I preview it I get the following error:
 
ReferenceError: 'AccountsApp' is not defined at main (script code:75:5)

I'm very new to scripts so I am not sure what I need to change or update to get past this. Thank you in advance for your help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 560a287d-c037-b6b7-5263-f90f07346531
* Version Independent ID: 149e1d90-8aa5-d5a4-5d86-6e8b0ee0849c
* Content: [Check for ads or keywords with broken URLs - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/scripts/solutions/check-ad-keyword-urls)
* Content Source: [Advertising/scripts/solutions/check-ad-keyword-urls.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/scripts/solutions/check-ad-keyword-urls.md)
* Service: **bing-ads-scripts**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@nintendork78 please confirm are you running the script in Microsoft Advertising UI or sandbox as described [here](https://docs.microsoft.com/en-us/advertising/scripts/get-started). Does any simple script run OK?

**Comment by nintendork78** [comment]
Thank you for responding. This is running in the Microsoft Advertising UI. Simpler example scripts, including the one in the link you supplied (check for 0 impression keywords) are running without issue.
