### ISSUE TITLE
Option 2 - How long should the access be valid for?

### ISSUE THREAD

**Issue by judelytics** [MicrosoftDocs/Advertising-docs#942]
When using the Option 2, how long should the access be good for? Even when following all the steps, my token expires after 1h...
I have a Microsoft Advertising Script sending data to a Google Sheet that I want to run daily, so I need long term access, but I do not know how.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3ce6eab-bca2-05fe-eda5-0a19f45b8d77
* Version Independent ID: 9390085d-bb86-e428-89c8-37afdba6c2b5
* Content: [Authenticating with Google services - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/scripts/examples/authenticating-with-google-services)
* Content Source: [Advertising/scripts/examples/authenticating-with-google-services.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/scripts/examples/authenticating-with-google-services.md)
* Service: **bing-ads-scripts**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
Great feedback, thanks! The access token typically is only valid for one hour. If you require access longer, a refresh token per option 3 is required. The documentation should be updated to clarify.
