### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by eeich82** [MicrosoftDocs/Advertising-docs#976]
Hi,

I would like to use the Bing ad disapproval script but the permissions required seem to be excessive and my company won't approve. Could the script be modified so that we'd specify a gsheet URL instead? https://docs.microsoft.com/en-us/advertising/scripts/solutions/get-disapproved-ads
<img width="324" alt="Screen Shot 2021-03-25 at 2 03 19 PM" src="https://user-images.githubusercontent.com/81383590/112531711-45b7c800-8d7e-11eb-8b16-80db557526e6.png">

**Comment by eric-urban** [comment]
@eeich82 - If I understand correctly this is a permissions issue to resolve with your company or if appropriate creating a separate Google account just for scripts and share whatever files the script uses with that account. This way you can still give permissions to access all files under the new account.
