### ISSUE TITLE
Negative Keywords report

### ISSUE THREAD

**Issue by wmurphy** [MicrosoftDocs/Advertising-docs#995]
Hello, looking through the documentation of the Report types, we cannot seem to find where we can download a report on Negative keywords. Does this report exist? What would be the best way to extract this information for reporting purposes?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 894c8834-7ad2-27be-a3b7-d8201300897a
* Version Independent ID: 45bb35da-28c5-960d-6536-270a2455360c
* Content: [Report Types - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/guides/report-types?view=bingads-13)
* Content Source: [Advertising/bingads-13/guides/report-types.md](https://github.com/MicrosoftDocs/Advertising-docs/blob/master/Advertising/bingads-13/guides/report-types.md)
* Service: **bing-ads**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@wmurphy  - You can use the [negative keyword conflict report](https://docs.microsoft.com/en-us/advertising/reporting-service/negativekeywordconflictreportrequest) to find out whether keywords and negative keywords conflict. Negative keywords don't have any performance reporting data. For more information please see [this help article](https://help.ads.microsoft.com/#apex/ads/en/56888/1).
